### ISSUE TITLE
conflicting values empty disjunction cue image

### ISSUE THREAD

**Issue by droogmic** [simonecarriero/rust-cargo-chef-dagger-action#1]
Awesome project.

I am running into this issue: https://github.com/a-b-street/osm2lanes/pull/239
Not sure if it's my understanding of cue that is failing me.

```
11:06PM FATAL failed to execute plan: actions.build.planner._dag."0"._dag."0"._pull.output.$dagger.fs._id: 2 errors in empty disjunction:
actions.build.planner._dag."0"._dag."0"._pull.output.$dagger.fs._id: conflicting values "1bf4171a-3fa6-4cd1-a1e6-768402adbbb8" and null (mismatched types string and null):
    ./cue.mod/pkg/dagger.io/dagger/core/image.cue:83:10
    ./cue.mod/pkg/dagger.io/dagger/types.cue:10:29
    ./cue.mod/pkg/github.com/simonecarriero/rust-cargo-chef-dagger-action/cargochef/main.cue:24:8
    ./cue.mod/pkg/github.com/simonecarriero/rust-cargo-chef-dagger-action/cargochef/main.cue:26:4
    ./cue.mod/pkg/github.com/simonecarriero/rust-cargo-chef-dagger-action/cargochef/main.cue:41:11
    ./cue.mod/pkg/github.com/simonecarriero/rust-cargo-chef-dagger-action/cargochef/main.cue:43:4
    ./cue.mod/pkg/universe.dagger.io/docker/build.cue:16:3
    ./cue.mod/pkg/universe.dagger.io/docker/build.cue:17:14
    ./cue.mod/pkg/universe.dagger.io/docker/pull.cue:23:9
    ./dagger.cue:8:1
    ./dagger.cue:17:10
actions.build.planner._dag."0"._dag."0"._pull.output.$dagger.fs._id: conflicting values "2ef4fa59-98d1-42b5-acdb-116459981fb0" and "1bf4171a-3fa6-4cd1-a1e6-768402adbbb8":
    ./cue.mod/pkg/github.com/simonecarriero/rust-cargo-chef-dagger-action/cargochef/main.cue:41:11
    ./cue.mod/pkg/github.com/simonecarriero/rust-cargo-chef-dagger-action/cargochef/main.cue:43:4
    ./cue.mod/pkg/universe.dagger.io/docker/build.cue:16:3
    ./cue.mod/pkg/universe.dagger.io/docker/build.cue:17:14
    ./dagger.cue:8:1
    ./dagger.cue:17:10
```

**Comment by simonecarriero** [comment]
Hi @droogmic, happy that you find it useful!

In my understanding dagger is still in early stage and sometimes error messages are not very clear, but there is [some effort going on to improve them](https://github.com/dagger/dagger/issues/613). For example, if you [search "empty disjunction" in the dagger GitHub issues](https://github.com/dagger/dagger/issues?q=is%3Aissue+is%3Aopen+empty+disjunction) you'll see some similar errors with temporary workarounds.

I fixed a problem that apparently was causing the empty disjunction error in some specific edge-cases. Could you try to update to v0.0.2 with `dagger project update github.com/simonecarriero/rust-cargo-chef-dagger-action@v0.0.2` and see if it works for you?

**Comment by droogmic** [comment]
aha, yes, that fixed it, thanks :D

https://github.com/a-b-street/osm2lanes/runs/7404203046?check_suite_focus=true
